pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               sh 'cd coit-backend1 && mvn install'
            }
        }
        stage('docker-build') {
            steps {
               sh 'cd coit-backend1 && docker build -t jagroopsingh/jenkins-practice .'
               sh 'docker images' 
            }
        }
        stage('docker-push') {
            steps {
               sh 'docker push jagroopsingh/jenkins-practice'
            }
    }
}
}
